"""Tests for meta-scrub.py. Every case builds its files in a fresh temporary directory and runs the tool the
way a caller runs it, as a subprocess. Cases that need pypdf, Pillow or ffmpeg skip when the machine lacks
them, and say so.

    python test-meta-scrub.py
"""
import io
import os
import shutil
import subprocess
import sys
import tempfile
import unittest
import zipfile

HERE = os.path.dirname(os.path.abspath(__file__))
TOOL = os.path.join(os.path.dirname(HERE), "meta-scrub.py")

CONTENT_TYPES = (b'<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n'
                 b'<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"/>')
CORE = ('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n'
        '<cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" '
        'xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" '
        'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">'
        '<dc:title>Draft</dc:title><dc:subject>s</dc:subject><dc:creator>python-docx</dc:creator>'
        '<cp:keywords>k</cp:keywords><dc:description>generated by a script</dc:description>'
        '<cp:lastModifiedBy>someone</cp:lastModifiedBy><cp:revision>1</cp:revision>'
        '<dcterms:created xsi:type="dcterms:W3CDTF">2026-10-08T10:00:00Z</dcterms:created>'
        '<cp:category>c</cp:category><cp:contentStatus>final</cp:contentStatus><cp:version>2</cp:version>'
        '</cp:coreProperties>')
APP = ('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n'
       '<Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties">'
       '<Template>Normal.dotm</Template><Application>LibreOffice/24.8$Windows_X86_64</Application>'
       '<Company>Somewhere</Company><TitlesOfParts>Sheet1</TitlesOfParts><AppVersion>16.0000</AppVersion>'
       '</Properties>')
BODY = b"<w:document>the words of the document</w:document>"


def has(module):
    try:
        __import__(module)
        return True
    except ImportError:
        return False


def read(path):
    with open(path, "rb") as f:
        return f.read()


def run(*args):
    return subprocess.run([sys.executable, TOOL] + list(args), capture_output=True, text=True)


def office(path, core=CORE, app=APP):
    with zipfile.ZipFile(path, "w") as z:
        z.writestr("[Content_Types].xml", CONTENT_TYPES, compress_type=zipfile.ZIP_STORED)
        z.writestr("docProps/core.xml", core, compress_type=zipfile.ZIP_DEFLATED)
        z.writestr("docProps/app.xml", app, compress_type=zipfile.ZIP_DEFLATED)
        z.writestr("word/document.xml", BODY, compress_type=zipfile.ZIP_DEFLATED)


class Base(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.mkdtemp(prefix="meta-scrub-")
        self.addCleanup(shutil.rmtree, self.tmp, True)

    def path(self, name):
        return os.path.join(self.tmp, name)


class OfficeFiles(Base):
    def test_every_named_property_is_cleared_and_every_other_part_stays_byte_for_byte(self):
        p = self.path("a.docx")
        office(p)
        done = run(p)
        self.assertEqual(0, done.returncode, done.stderr)
        self.assertIn("cleared", done.stdout)
        with zipfile.ZipFile(p) as z:
            names = [i.filename for i in z.infolist()]
            core = z.read("docProps/core.xml").decode()
            app = z.read("docProps/app.xml").decode()
            self.assertEqual(BODY, z.read("word/document.xml"))
            self.assertEqual(CONTENT_TYPES, z.read("[Content_Types].xml"))
            self.assertEqual(zipfile.ZIP_STORED, z.getinfo("[Content_Types].xml").compress_type)
        self.assertEqual(["[Content_Types].xml", "docProps/core.xml", "docProps/app.xml", "word/document.xml"], names)
        for gone in ("python-docx", "someone", "Draft", "generated by a script", "final", ">k<", ">c<", ">2<"):
            self.assertNotIn(gone, core)
        for gone in ("LibreOffice", "Somewhere", "Normal.dotm", "16.0000"):
            self.assertNotIn(gone, app)
        self.assertIn("<dc:creator/>", core)
        self.assertIn("2026-10-08T10:00:00Z", core)  # dates name no program and stay
        self.assertIn("<TitlesOfParts>Sheet1</TitlesOfParts>", app)  # content, not a generator

    def test_check_names_the_fields_changes_nothing_and_exits_1(self):
        p = self.path("a.docx")
        office(p)
        before = read(p)
        done = run("--check", p)
        self.assertEqual(1, done.returncode)
        self.assertIn("creator", done.stdout)
        self.assertIn("Application", done.stdout)
        self.assertEqual(before, read(p))

    def test_a_cleared_file_passes_the_check_and_a_second_run_changes_nothing(self):
        p = self.path("a.pptx")
        office(p)
        run(p)
        after = read(p)
        self.assertEqual(0, run("--check", p).returncode)
        self.assertEqual("", run(p).stdout)
        self.assertEqual(after, read(p))

    @unittest.skipUnless(has("openpyxl"), "needs openpyxl")
    def test_a_workbook_saved_by_openpyxl_is_clean_after_and_still_opens(self):
        import openpyxl
        p = self.path("book.xlsx")
        wb = openpyxl.Workbook()
        wb.active["A1"] = 42
        wb.properties.creator = "openpyxl"
        wb.save(p)
        self.assertEqual(1, run("--check", p).returncode)
        self.assertEqual(0, run(p).returncode)
        self.assertEqual(0, run("--check", p).returncode)
        self.assertEqual(42, openpyxl.load_workbook(p).active["A1"].value)


@unittest.skipUnless(has("PIL"), "needs Pillow")
class Images(Base):
    def test_png_text_chunks_go_and_the_pixels_stay(self):
        from PIL import Image, PngImagePlugin
        p = self.path("a.png")
        info = PngImagePlugin.PngInfo()
        info.add_text("Software", "Some Editor 3.1")
        Image.new("RGB", (4, 3), (10, 20, 30)).save(p, pnginfo=info)
        self.assertEqual(1, run("--check", p).returncode)
        self.assertEqual(0, run(p).returncode)
        self.assertNotIn(b"Some Editor", read(p))
        with Image.open(p) as im:
            self.assertEqual((10, 20, 30), im.getpixel((1, 1)))
        self.assertEqual(0, run("--check", p).returncode)

    def test_jpeg_exif_goes_and_the_image_still_decodes(self):
        from PIL import Image
        p = self.path("a.jpg")
        exif = Image.Exif()
        exif[0x0131] = "Some Editor 3.1"  # Software
        exif[0x013B] = "someone"  # Artist
        Image.new("RGB", (16, 16), (200, 100, 50)).save(p, exif=exif, quality=95)
        self.assertEqual(1, run("--check", p).returncode)
        self.assertEqual(0, run(p).returncode)
        raw = read(p)
        self.assertNotIn(b"Some Editor", raw)
        self.assertNotIn(b"someone", raw)
        with Image.open(p) as im:
            im.load()
            self.assertEqual((16, 16), im.size)

    def test_a_turned_photo_is_refused_and_left_as_it_is(self):
        from PIL import Image
        p = self.path("turned.jpg")
        exif = Image.Exif()
        exif[0x0112] = 6  # Orientation: shown turned 90 degrees
        Image.new("RGB", (8, 4)).save(p, exif=exif)
        before = read(p)
        done = run(p)
        self.assertEqual(2, done.returncode)
        self.assertIn("orientation 6", done.stderr)
        self.assertEqual(before, read(p))
        self.assertEqual([], [n for n in os.listdir(self.tmp) if "scrub-tmp" in n])


@unittest.skipUnless(has("pypdf") and has("fitz"), "needs pypdf and PyMuPDF")
class Pdf(Base):
    def test_pdf_information_and_xmp_go_and_the_text_stays(self):
        import fitz
        p = self.path("a.pdf")
        doc = fitz.open()
        doc.new_page().insert_text((72, 72), "hello reader")
        doc.set_metadata({"author": "someone", "creator": "Some Writer", "producer": "Some Library 1.0"})
        doc.set_xml_metadata('<x:xmpmeta xmlns:x="adobe:ns:meta/"><rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"/></x:xmpmeta>')
        doc.save(p)
        self.assertIn(b"xmpmeta", read(p))
        self.assertEqual(1, run("--check", p).returncode)
        self.assertEqual(0, run(p).returncode)
        raw = read(p)
        for gone in (b"someone", b"Some Writer", b"Some Library", b"pypdf", b"xmpmeta"):
            self.assertNotIn(gone, raw)
        self.assertIn("hello reader", fitz.open(p)[0].get_text())
        self.assertEqual(0, run("--check", p).returncode)


@unittest.skipUnless(shutil.which("ffmpeg") and shutil.which("ffprobe"), "needs ffmpeg and ffprobe")
class Video(Base):
    def frames(self, path):
        out = subprocess.run(["ffprobe", "-v", "error", "-count_frames", "-select_streams", "v",
                              "-show_entries", "stream=nb_read_frames", "-of", "csv=p=0", path],
                             capture_output=True, text=True, check=True).stdout
        return int(out.strip())

    def clip(self, name, *audio_flags):
        p = self.path(name)
        made = subprocess.run(["ffmpeg", "-v", "error", "-f", "lavfi", "-i", "testsrc=size=64x64:rate=10:duration=1",
                               "-f", "lavfi", "-i", "sine=duration=1", "-c:v", "libx264", "-c:a", "aac"]
                              + list(audio_flags) + ["-metadata", "title=draft", "-metadata", "comment=made by a script", p],
                              capture_output=True, text=True)
        if made.returncode != 0:
            self.skipTest("this ffmpeg cannot make an x264 clip: " + made.stderr[-200:])
        return p

    def test_encoder_tags_and_the_x264_note_go_and_every_frame_stays(self):
        p = self.clip("clip.mp4", "-flags:a", "+bitexact")
        self.assertIn(b"x264 - core", read(p))
        self.assertEqual(1, run("--check", p).returncode)
        done = run(p)
        self.assertEqual(0, done.returncode, done.stderr)
        raw = read(p)
        for gone in (b"x264 - core", b"Lavf", b"Lavc", b"made by a script"):
            self.assertNotIn(gone, raw)
        self.assertEqual(10, self.frames(p))
        decoded = subprocess.run(["ffmpeg", "-v", "error", "-i", p, "-f", "null", "-"], capture_output=True, text=True)
        self.assertEqual("", decoded.stderr)
        self.assertEqual(0, run("--check", p).returncode)

    def test_a_name_inside_the_audio_frames_is_refused_and_the_file_left_as_it_is(self):
        p = self.clip("loud.mp4")
        before = read(p)
        self.assertIn(b"Lavc", before)  # ffmpeg's AAC encoder writes it into the first frame
        done = run(p)
        self.assertEqual(2, done.returncode)
        self.assertIn("would still name", done.stderr)
        self.assertIn("bitexact", done.stderr)
        self.assertEqual(before, read(p))
        self.assertEqual([], [n for n in os.listdir(self.tmp) if "scrub-tmp" in n])


class Walk(Base):
    def test_a_folder_is_walked_without_git_node_modules_or_venv_and_other_kinds_are_ignored(self):
        for sub in ("docs", ".git", "node_modules", ".venv"):
            os.makedirs(self.path(sub))
            office(os.path.join(self.path(sub), "a.docx"))
        with open(self.path("notes.txt"), "w") as f:
            f.write("creator: someone")
        done = run("--check", self.tmp)
        self.assertEqual(1, done.returncode)
        self.assertEqual(1, len(done.stdout.strip().splitlines()))
        self.assertIn(os.path.join("docs", "a.docx"), done.stdout)

    def test_a_damaged_file_is_named_and_the_rest_still_run(self):
        with open(self.path("bad.docx"), "wb") as f:
            f.write(b"not a zip")
        office(self.path("good.docx"))
        done = run(self.tmp)
        self.assertEqual(2, done.returncode)
        self.assertIn("bad.docx", done.stderr)
        self.assertEqual(0, run("--check", self.path("good.docx")).returncode)

    def test_a_missing_path_or_no_argument_exits_2(self):
        self.assertEqual(2, run(self.path("nothing-here.docx")).returncode)
        self.assertEqual(2, run().returncode)

    def test_the_tool_holds_no_em_dash(self):
        with io.open(TOOL, encoding="utf-8") as f:
            self.assertNotIn("—", f.read())


if __name__ == "__main__":
    unittest.main(verbosity=1)
